### ISSUE TITLE
Rest Controller difference in Pimcore 6.6 and 11

### ISSUE THREAD

**Issue by mishrasantosh831** [valantic-at/ProcessManager#207]
I've just started using pimcore 11 and installed Process Manager(v5.0.12). I stumbled upon an error when I tried triggering a process in process manager using rest APIs. The executeAction function in rest controller(./vendor/elements/process-manager-bundle/src/Controller/RestController.php) has a different implemetation:

Pim 6.6(Line no. 87):
=============
$config = $list->load()[0];

Pim 11(Line No. 73):
=============
$config = $list->current();

The above is the reason for my error in Pim 11. Kindly provide a solution for the same.

**Comment by ctippler** [comment]
Thx for the bugfix
