### ISSUE TITLE
Refresh Background Processes Window

### ISSUE THREAD

**Issue by scarpeneintesys** [valantic-at/ProcessManager#209]
Hi,
i used the bundle to create a command that is executed from a custom button in the admin panel. After creating the process is there a way to show/update the "Background Processes" window?
![image](https://github.com/elements-at/ProcessManager/assets/147415813/bf4ac0b9-5bb3-4e42-8cdc-67b322c40eda)

This feature can be useful when using Rest API too. For example an external tool create a process (so is not the user directly) and the user can see the process after few seconds the api is called instead of reloading the pimcore admin page.

Thank you.

**Comment by ctippler** [comment]
Hi,
in theory a JavaScript call to
`processmanagerPlugin.initActiveProcesses()` 

should show them.
BR, Christian
