### ISSUE TITLE
trait `ExecutionTraitClass` removed in bugfix release

### ISSUE THREAD

**Issue by aashan10** [valantic-at/ProcessManager#217]
The trait `ExecutionTraitClass` was not marked as internal and is used throughout our project. It was removed recently (https://github.com/valantic-at/ProcessManager/commit/bb3ccb3df578da8aef28a0485c877d2eb545d730) and is causing our console to not work anymore. 

Shouldn't it be deprecated first and then removed in later releases?

**Comment by ctippler** [comment]
Hi,
oh, sorry - i was confused because the Pimcore\Cache\Runtime doesn't exist in Pimcore 11 anymore. but for Pimcore 10 it's still valid. I readded the class and marked it as deprecated. 

BR, Christian
